apiVersion: v1
data:
{{- if .Values.PipelineSecrets.DockerConfig }}
  config.json: {{ .Values.PipelineSecrets.DockerConfig | quote }}
{{- else }}
  config.json: ""
{{- end }}
kind: Secret
metadata:
  name: jenkins-docker-cfg
type: Opaque