apiVersion: v1
kind: Secret
metadata:
  name: jenkins-docker-cfg
type: Opaque
data:
{{- if .Values.PipelineSecrets.DockerConfig }}
  config.json: "{{ .Values.PipelineSecrets.DockerConfig | b64enc }}"
{{- else }}
  config.json: ""
{{- end }}