{{- if .Values.JenkinsXGKEServiceAccount }}
apiVersion: v1
data:
  filename: {{ .Values.JenkinsXGKEServiceAccount.Filename | b64enc | quote }}
  password: {{ .Values.JenkinsXGKEServiceAccount.Data | b64enc | quote }}
kind: Secret
metadata:
  labels:
    jenkins.io/credentials-type: secretFile
  name: gke-sa
type: Opaque
{{- end }}