{{- if .Values.JenkinsXGitHub }}
apiVersion: v1
data:
  username: {{ .Values.JenkinsXGitHub.Name | quote }}
  password: {{ .Values.JenkinsXGitHub.Password | quote }}
kind: Secret
metadata:
  labels:
    jenkins.io/credentials-type: usernamePassword
  name: jenkins-x-github
type: Opaque
{{- end }}